### ISSUE TITLE
Confused over sorting scripts

### ISSUE THREAD

**Issue by ghost** [sri-arjuna/Empyrion-Scripts#1]
Looking at https://github.com/sri-arjuna/Empyrion-Scripts/blob/main/3.%20REA%20-%20noVolume/Sort/SortFoodMedic.lua

We tried to the script but couldnt get it to work.

We named the input folder: Drop Box
which we gleamed from:
`	{{~#items E.S '*Drop Box*'}}`
Named a fridge as "Fridge-food"
and renamed this line:
`	{{~#devices @root.E.S 'Fridge-food'}}`
Named a fridge as "Fridge-medic"
and renamed this line:
`	{{~#devices @root.E.S 'Fridge-medic}}`

added to an lcd screen called "Script:FoodTransfer"
made an lcd called "FoodTransfer"

I loaded the drop box with medical supplies and food.... nothing happened.
Turned on and off the ship...nothing continued to happen.

Other scripts are working well, but this one elludes me.

I wanted see this in action so i could get my head around this very wierd scripting system and hopefully work my own sorting system out.

**Comment by sri-arjuna** [comment]
For this script, you do need to have 2 dashes "-" in the name.
Working with only 2 strings (1 dash) will not work.
Most other sorting scripts will attempt to look for the item id for the last of the 3 strings (split from '-').

That said, it will also work with a simple workaround:

    Fridge-Food-1

Furthemore, this will allow you to add more fridges, once this one is full, and the sorting script will then move all new food items to nr 2, then 3.. and so on.
